language: python

python:
  - "2.7"

env:
  - DJANGO="django==1.6"
  - DJANGO="django==1.5.5"

install:
  - pip install $DJANGO
  - pip install "djangorestframework==2.3.12"
  - export PYTHONPATH=.

script:
  - cd latitude && python manage.py test

